"""message chart type

Revision ID: 36f195dffc29
Revises: b70b09f0c11c
Create Date: 2026-08-02 14:48:26.846465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36f195dffc29'
down_revision: Union[str, Sequence[str], None] = 'b70b09f0c11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('chart_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='none'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'chart_type')
    # ### end Alembic commands ###
