"""message type and jsonb content

Revision ID: b70b09f0c11c
Revises: 8ae12eac63e6
Create Date: 2026-08-02 14:38:09.553805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b70b09f0c11c'
down_revision: Union[str, Sequence[str], None] = '8ae12eac63e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='content::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='content::text')
    op.drop_column('message', 'type')
    # ### end Alembic commands ###
